---
seo
---
keywords:
    deployment
    microservices
    aks
    azure
    asp.net core
    orchestration
potential keyword focii:

-------
content
-------

intro tweet?: https://twitter.com/CarmenCrincoli/status/1158772188402475010

follow tutorial (https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough):
1. az group create --name helloMicroserviceGroup --location eastus
2. az aks create --resource-group helloMicroserviceGroup --name helloMicroserviceAks --node-count 3 --node-vm-size Standard_B2s --enable-addons monitoring --generate-ssh-keys
3. az aks get-credentials --resource-group helloMicroserviceGroup --name helloMicroserviceAks

kubectl create -f admission.yaml
kubectl create -f crd.yaml
kubectl create -f operator-role.yaml
kubectl create -f operator-service-account.yaml
kubectl create -f operator-role-binding.yaml
kubectl create -f operator-deployment.yaml
kubectl create -f secret.yaml
kubectl create -f couchbase-cluster.yaml (takes about 3 min for a single node)
kubectl create -f hello-microservice.yaml

port forwarding:
kubectl port-forward <pod name> 1111:1111
kubectl port-forward cb-hellomicroservices-0000 8891:8091
kubectl port-forward hello-microservice-app-deployment-8487dfd45d-ntlvl 5000:80

DNS SRV:
From Brant: You should be able to put your connection string as "couchbase://cb-hellomicroservices-srv".  The cb-hello-microservices-srv should be creating a DNS entry for "_couchbase._tcp.cb-hello-microservices-srv.default.svc.cluster.local". However, your DNS suffix for your pods, if in the same namespace, should already be "default.svc.cluster.local", so that part shouldn't be required. _couchbase._tcp is automatically prepended by the .NET extension, so you leave that part off, too.

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#srv-records

view UI/dashboard:
az aks browse --resource-group helloMicroserviceGroup --name helloMicroserviceAks

expose service:
https://blogs.msdn.microsoft.com/najib/2017/05/27/web-api-with-docker-and-kubernetes/
kubectl expose deployments hello-microservice-app-deployment --port=80 --type=LoadBalancer
kubectl get services (get IP address, go to http://<ip address>)

when you're done don't forget to delete the resource group if you don't need it anymore, and save your money!
az group delete --name helloMicroserviceGroup

links:
https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough
https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard
https://github.com/deniswsrosa/microservices-on-kubernetes (associated blog post(s))

links for SEO:
https://docs.microsoft.com/en-us/azure/aks/
https://kubernetes.io/
link back to asp.net core microservices post