{
 "title": "Couchbase 6 Multi-Cluster Monitoring",
 "description": "Couchbase 6 dashboard, created for totvslabs/couchbase-exporter",
 "tags": [ "couchbase" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(couchbase_node_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "General ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Balanced",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "couchbase_cluster_balanced{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rebalance Progress",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "couchbase_task_rebalance_progress{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Compacting Progress",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(couchbase_task_compacting_progress{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Bucket RAM Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 * (sum by (bucket) (couchbase_bucket_basicstats_memused_bytes{instance=\"$instance\"})) / sum by (bucket) (couchbase_bucket_stats_ep_max_size_bytes{instance=\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Server Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(couchbase_node_healthy{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Unhealthy Server Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(couchbase_node_healthy{instance=\"$instance\"} == 0) or (1-absent(couchbase_node_healthy{instance=\"$instance\"} == 0))"
    }
   ]
  },
  { "title": "General ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Balanced",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "couchbase_cluster_balanced{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rebalance Progress",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "couchbase_task_rebalance_progress{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Compacting Progress",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(couchbase_task_compacting_progress{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Bucket RAM Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 * (sum by (bucket) (couchbase_bucket_basicstats_memused_bytes{instance=\"$instance\"})) / sum by (bucket) (couchbase_bucket_stats_ep_max_size_bytes{instance=\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Server Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(couchbase_node_healthy{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Unhealthy Server Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(couchbase_node_healthy{instance=\"$instance\"} == 0) or (1-absent(couchbase_node_healthy{instance=\"$instance\"} == 0))"
    }
   ]
  },
  { "title": "Details ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "instance" },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (couchbase_bucket_stats_cmd_set{instance=\"$instance\"}) + sum by (bucket) (couchbase_bucket_stats_cmd_get{instance=\"$instance\"})",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "couchbase_bucket_stats_ep_cache_miss_rate{instance=\"$instance\"}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  { "title": "Details ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (couchbase_bucket_stats_cmd_set{instance=\"$instance\"}) + sum by (bucket) (couchbase_bucket_stats_cmd_get{instance=\"$instance\"})",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "couchbase_bucket_stats_ep_cache_miss_rate{instance=\"$instance\"}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  { "title": "Queries ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }, "repeat": "instance" },
  {
   "title": "Gets / Sets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "couchbase_bucket_stats_cmd_set{instance=\"$instance\"}",
     "legendFormat": "Sets on {{ bucket }}"
    },
    {
     "expr": "couchbase_bucket_stats_cmd_get{instance=\"$instance\"}",
     "legendFormat": "Gets on {{ bucket }}"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "couchbase_bucket_stats_evictions{instance=\"$instance\"}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Miss Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "couchbase_bucket_stats_ep_cache_miss_rate{instance=\"$instance\"}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  { "title": "Queries ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Gets / Sets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "couchbase_bucket_stats_cmd_set{instance=\"$instance\"}",
     "legendFormat": "Sets on {{ bucket }}"
    },
    {
     "expr": "couchbase_bucket_stats_cmd_get{instance=\"$instance\"}",
     "legendFormat": "Gets on {{ bucket }}"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "couchbase_bucket_stats_evictions{instance=\"$instance\"}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Miss Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "couchbase_bucket_stats_ep_cache_miss_rate{instance=\"$instance\"}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Memory ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * couchbase_bucket_basicstats_memused_bytes{instance=\"$instance\"} / couchbase_bucket_stats_ep_max_size_bytes",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Items Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_curr_items{instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Hard Out of Memory Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(couchbase_bucket_stats_ep_oom_errors{instance=\"$instance\"}[5m])",
       "legendFormat": "{{ bucket }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * couchbase_bucket_basicstats_memused_bytes{instance=\"$instance\"} / couchbase_bucket_stats_ep_max_size_bytes",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Items Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_curr_items{instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Hard Out of Memory Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(couchbase_bucket_stats_ep_oom_errors{instance=\"$instance\"}[5m])",
       "legendFormat": "{{ bucket }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compacting ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Fragmentation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_couch_docs_fragmentation{instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Compaction Progress",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "couchbase_task_compacting_progress{instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compacting ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fragmentation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_couch_docs_fragmentation{instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Compaction Progress",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "couchbase_task_compacting_progress{instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rebalance ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Rebalance Progress",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "couchbase_task_rebalance_progress{instance=\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "DCP Replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replica_producers{instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}: DCP Senders"
      },
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replicas{instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}: DCP Connections"
      }
     ]
    },
    {
     "title": "Items Sent / Remaining",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replica_items_sent{instance=\"$instance\"}",
       "legendFormat": "Sent on {{ bucket }}"
      },
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replica_items_remaining{instance=\"$instance\"}",
       "legendFormat": "Remaining on {{ bucket }}"
      }
     ]
    },
    {
     "title": "Speed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replica_total_bytes{instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rebalance ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rebalance Progress",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "couchbase_task_rebalance_progress{instance=\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "DCP Replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replica_producers{instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}: DCP Senders"
      },
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replicas{instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}: DCP Connections"
      }
     ]
    },
    {
     "title": "Items Sent / Remaining",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replica_items_sent{instance=\"$instance\"}",
       "legendFormat": "Sent on {{ bucket }}"
      },
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replica_items_remaining{instance=\"$instance\"}",
       "legendFormat": "Remaining on {{ bucket }}"
      }
     ]
    },
    {
     "title": "Speed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replica_total_bytes{instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    }
   ]
  },
  {
   "title": "XDCR ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Items Sent / Remaining",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_items_remaining{instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}: Remaining"
      },
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_items_sent{ instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}: Sent"
      }
     ]
    },
    {
     "title": "Speed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_total_bytes{ instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Backlog Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_total_backlog_size{ instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "DCP",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_connections{ instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}: connections"
      },
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_producers{ instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}: producers"
      }
     ]
    }
   ]
  },
  {
   "title": "XDCR ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Items Sent / Remaining",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_items_remaining{instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}: Remaining"
      },
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_items_sent{ instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}: Sent"
      }
     ]
    },
    {
     "title": "Speed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_total_bytes{ instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Backlog Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_total_backlog_size{ instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "DCP",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_connections{ instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}: connections"
      },
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_producers{ instance=\"$instance\"}",
       "legendFormat": "{{ bucket }}: producers"
      }
     ]
    }
   ]
  },
  {
   "title": "Scrape times ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "couchbase_cluster_scrape_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "cluster"
      },
      {
       "expr": "couchbase_bucket_scrape_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "bucket"
      },
      {
       "expr": "couchbase_node_scrape_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "node"
      },
      {
       "expr": "couchbase_task_scrape_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "task"
      }
     ]
    }
   ]
  },
  {
   "title": "Scrape times ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "couchbase_cluster_scrape_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "cluster"
      },
      {
       "expr": "couchbase_bucket_scrape_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "bucket"
      },
      {
       "expr": "couchbase_node_scrape_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "node"
      },
      {
       "expr": "couchbase_task_scrape_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "task"
      }
     ]
    }
   ]
  }
 ]
}