== Using Key/Value Lookup in ASP.NET Core

SQL isn't the only way to read data from Couchbase. Remember those IDs? If you know the ID of a document you want to look up, you can do so with the key/value API.

Why use the key/value API? Because it's the fastest way to access data in Couchbase. It will perform an in-memory lookup, and it will not engage the Query or Index services. If your document is cached, you will likely get microsecond access time.

Create another endpoint in GiftsController called Get():

[source,C#,indent=0]
----
[HttpGet]
[Route("api/get/{id}")]
public async Task<IActionResult> Get(string id)
{
    var bucket = await _bucketProvider.GetBucketAsync("demo");
    var collection = await bucket.CollectionAsync("wishlist");

    var item = await collection.GetAsync(id);

    return Ok(item.ContentAs<WishlistItem>());
}
----

In this example, we don't need a cluster, but we do need a collection. Note that since the wishlist collection is in the "_default" scope, we can skip right past getting the scope and go directly from bucket to collection.

When the item is returned from `GetAsync`, it's in an `IGetResult` object. Couchbase doesn't store C# objects, it stores JSON. So, to serialize to a `WishlistItem` object, use `item.ContentAs<WishlistItem>`. This API gives you flexibility: a document returned from Couchbase could be serialized to `WishlistItem` here and perhaps `AmazonWishlistItem` in another part of the application.
