= Tips for AsciiDoc
include::links.adoc[]

== Command line processing:

[source,shell]
----
asciidoctor -a allow-uri-read -b html5 blogpost.adoc
----

== Visual Studio Code support
Get the https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode[preview extension]

Add this to user or workspace settings to allow importing of content via URI

[source]
"asciidoc.html_generator": "asciidoctor -a allow-uri-read -o-"

To output html5 instead of xhtml, add `-b html5`

== Pull content directly from GitHub

Use links to raw content.

e.g. `include::https://raw.githubusercontent.com/couchbaselabs/xdcr-java-sample/master/src/main/java/com/couchbase/server/xdcr/ClusterBasics.java[]`

This works with images, too.

== Shorthand links

Keep a file of commonly used links and shorthand codes.  For example AsciiDoc automatically replaces \{CBS}
with the link {CBS}.  Or, don't supply default text and add it on use, e.g. {XDCR-}[XDCR is cool].

See https://github.com/couchbaselabs/blog-source-code/blob/master/Greeley/links.adoc[links.adoc]

== Use tags

With tags, you can automate including code segments from complete source.
See http://asciidoctor.org/docs/user-manual/#include-partial[]

== Use callouts

Number code lines for reference.  This doesn't currently translate well to WordPress.
See http://asciidoctor.org/docs/user-manual/#callouts[]

== Linked images

image:https://img.shields.io/badge/License-Apache%202.0-blue.svg[link="http://www.apache.org/licenses/LICENSE-2.0"]

image:https://lh3.googleusercontent.com/5JiISK4fWHJvXxBVOtVvXLGsXud6ZS5XZ-_KzH17pO-LvjwWKRWUveErQ6_RcxDnLx8dxm7LRS9zwt-j9BOaCZnod8Zfmgj8QrN_vbmKmwoTG8bwo6jkVPU2n9iaTnIn3KHFn9_bt2ygkiBSJkJ6V_8bdOmyeJDbbaeGG5QhV48xXr-_bkNl_4-GfPDBR4NWCV_T_hReoeo7iab7zib1GlHQqYQFi1LRhT0VtZIgA-EW4uSwYHCoQdESHYc8cvtsMwadygNzrAlT_XJsUDVzrXmfxlQgGgjbA1wi_bRIfUDskT4WWT8KRTHtQkvEDiaohiBWTYHOVwAJmmWaximfjyCLGYLlSxALxTq_LNUeZq3yXY2qA_6q9NwhHpwqlq8EJGUSUSvz0Y5o0ON5wxK2R7EFM_6DNq1YFKAKzo8zAJcu-uE05Em7e-07b8-09el2lKEQUQ6EVYPwi8y5jLRI25y5DC4UBUwkZFvgH0VQovoHiSe5UDYeTqu2KXfXo7e4P0gOzPk3C9FcT42JE-K_SVjwg12cQI8ZymoQ1X66x694MhjLr2N6RJD-qsv2Pnyz=w2878-h1516[link="https://lh3.googleusercontent.com/5JiISK4fWHJvXxBVOtVvXLGsXud6ZS5XZ-_KzH17pO-LvjwWKRWUveErQ6_RcxDnLx8dxm7LRS9zwt-j9BOaCZnod8Zfmgj8QrN_vbmKmwoTG8bwo6jkVPU2n9iaTnIn3KHFn9_bt2ygkiBSJkJ6V_8bdOmyeJDbbaeGG5QhV48xXr-_bkNl_4-GfPDBR4NWCV_T_hReoeo7iab7zib1GlHQqYQFi1LRhT0VtZIgA-EW4uSwYHCoQdESHYc8cvtsMwadygNzrAlT_XJsUDVzrXmfxlQgGgjbA1wi_bRIfUDskT4WWT8KRTHtQkvEDiaohiBWTYHOVwAJmmWaximfjyCLGYLlSxALxTq_LNUeZq3yXY2qA_6q9NwhHpwqlq8EJGUSUSvz0Y5o0ON5wxK2R7EFM_6DNq1YFKAKzo8zAJcu-uE05Em7e-07b8-09el2lKEQUQ6EVYPwi8y5jLRI25y5DC4UBUwkZFvgH0VQovoHiSe5UDYeTqu2KXfXo7e4P0gOzPk3C9FcT42JE-K_SVjwg12cQI8ZymoQ1X66x694MhjLr2N6RJD-qsv2Pnyz=w2878-h1516",width=96]

== GitHub tips

https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74
